"""Add is_admin to User model

Revision ID: 351bd137d1e1
Revises: fcf32bbf0db9
Create Date: 2024-06-21 12:26:53.991893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '351bd137d1e1'
down_revision = 'fcf32bbf0db9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
