"""Update Bill model with detailed information

Revision ID: 4263fbb86d7e
Revises: 741b4acfaa64
Create Date: 2024-06-21 21:08:34.040581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4263fbb86d7e'
down_revision = '741b4acfaa64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docket_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('chamber', sa.String(length=10), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hearing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('committee', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_year', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('general_status', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('house_status', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('senate_status', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('docket_link', sa.String(length=300), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('docket_link')
        batch_op.drop_column('senate_status')
        batch_op.drop_column('house_status')
        batch_op.drop_column('general_status')
        batch_op.drop_column('title')
        batch_op.drop_column('session_year')

    op.drop_table('hearing')
    op.drop_table('docket_entry')
    # ### end Alembic commands ###
