"""Add category to Bill model

Revision ID: 741b4acfaa64
Revises: c9aa8d424217
Create Date: 2024-06-21 19:09:05.199004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741b4acfaa64'
down_revision = 'c9aa8d424217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_bills',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'bill_id')
    )
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_bill_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bill_category'))
        batch_op.drop_column('category')

    op.drop_table('user_bills')
    # ### end Alembic commands ###
