"""Initial migration

Revision ID: c9aa8d424217
Revises: 351bd137d1e1
Create Date: 2024-06-21 16:33:42.724449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9aa8d424217'
down_revision = '351bd137d1e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('html_link', sa.String(length=300), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_superuser', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('is_superuser')

    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_column('html_link')
        batch_op.drop_column('full_text')

    # ### end Alembic commands ###
